// Bundles the embedded extension runtime into Tonycast/Resources/RaycastRuntime.generated.js.
//
//   pnpm install && node gen-enums.mjs && node build.mjs
//
// The output is committed (like EmojiData.generated.swift) so building Tonycast never needs Node.

import { build } from "esbuild";
import { mkdirSync, statSync, writeFileSync } from "node:fs";
import { dirname, resolve } from "node:path";

const outFile = resolve("../../Tonycast/Resources/RaycastRuntime.generated.js");
const dev = process.argv.includes("--dev");

mkdirSync(dirname(outFile), { recursive: true });

const result = await build({
  entryPoints: ["src/index.js"],
  bundle: true,
  format: "iife",
  platform: "neutral",
  // JavaScriptCore on macOS 26 is fully modern; no downlevelling needed.
  target: ["es2022"],
  minify: !dev,
  sourcemap: false,
  legalComments: "none",
  write: false,
  define: {
    "process.env.NODE_ENV": dev ? '"development"' : '"production"',
    __DEV__: dev ? "true" : "false",
  },
  banner: {
    js: "// Generated by Tools/raycast-runtime — do not edit. Regenerate with `node build.mjs`.",
  },
});

for (const warning of result.warnings) console.warn(warning.text);

const [output] = result.outputFiles;
// `__tonycastCompile` has to compile in the *global* scope so the extension bundle it evaluates can't
// see the runtime's own module locals. It is installed by Swift, not here.
writeFileSync(outFile, output.text);

const { size } = statSync(outFile);
console.log(`RaycastRuntime.generated.js — ${(size / 1024).toFixed(1)} KB${dev ? " (dev)" : ""}`);
